-- NOIRÉ launch catalog. Generated by scripts/generate-seed.mjs — edit scripts/catalog.mjs instead.
-- Safe to re-run: products are upserted by slug and variants by SKU.

-- NOIRÉ 01 — Santal Obscur
insert into public.noire_products (number, name, slug, description, short_description, currency, category, gender, fragrance_family, secondary_family, top_notes, heart_notes, base_notes, moods, scent_profiles, longevity, sillage, accent_color, image_url, gallery_images, sales_count, sort_order, featured, bestseller, new_arrival, created_at)
values (1, 'Santal Obscur', 'noire-01', 'A low-lit room after the guests have gone. Saffron and pink pepper strike first, then settle into creamy sandalwood and cedar that has been gently smoked over papyrus. A base of amber and soft leather lingers on skin long into the night — quiet, assured and unmistakably yours.', 'Smoked cedar, saffron and warm amber', 'NGN', 'Eau de Parfum', 'unisex', 'woody', 'amber', array['Saffron', 'Pink pepper', 'Cardamom']::text[], array['Sandalwood', 'Smoked cedar', 'Papyrus']::text[], array['Amber', 'Soft leather', 'Musk']::text[], array['after-dark', 'quiet-luxury']::text[], array['woody', 'warm', 'mysterious']::text[], '10–12 hours', 'Moderate to strong', '#5B4636', '/images/products/noire-01/front.svg', array['/images/products/noire-01/front.svg', '/images/products/noire-01/still.svg', '/images/products/noire-01/detail.svg']::text[], 412, 1, true, true, false, now() - interval '120 days')
on conflict (slug) do update set
  number = excluded.number, name = excluded.name, description = excluded.description,
  short_description = excluded.short_description, category = excluded.category, gender = excluded.gender,
  fragrance_family = excluded.fragrance_family, secondary_family = excluded.secondary_family,
  top_notes = excluded.top_notes, heart_notes = excluded.heart_notes, base_notes = excluded.base_notes,
  moods = excluded.moods, scent_profiles = excluded.scent_profiles, longevity = excluded.longevity,
  sillage = excluded.sillage, accent_color = excluded.accent_color, image_url = excluded.image_url,
  gallery_images = excluded.gallery_images, sort_order = excluded.sort_order, featured = excluded.featured,
  bestseller = excluded.bestseller, new_arrival = excluded.new_arrival;
insert into public.noire_product_variants (product_id, size_ml, price, stock_quantity, sku)
values
  ((select id from public.noire_products where slug = 'noire-01'), 30, 54000, 24, 'NO01-30'),
  ((select id from public.noire_products where slug = 'noire-01'), 50, 85000, 18, 'NO01-50'),
  ((select id from public.noire_products where slug = 'noire-01'), 100, 126000, 12, 'NO01-100')
on conflict (sku) do update set price = excluded.price, stock_quantity = excluded.stock_quantity;

-- NOIRÉ 02 — Velvet Amber
insert into public.noire_products (number, name, slug, description, short_description, currency, category, gender, fragrance_family, secondary_family, top_notes, heart_notes, base_notes, moods, scent_profiles, longevity, sillage, accent_color, image_url, gallery_images, sales_count, sort_order, featured, bestseller, new_arrival, created_at)
values (2, 'Velvet Amber', 'noire-02', 'Amber the way it should be: dense, glowing and slow to fade. Mandarin and clove open onto a heart of labdanum and benzoin softened with orris, before vanilla absolute and tonka bean wrap everything in warmth. An extrait concentration for evenings that deserve to be remembered.', 'Labdanum, vanilla and a trace of clove', 'NGN', 'Extrait de Parfum', 'unisex', 'amber', 'gourmand', array['Mandarin', 'Clove', 'Pink pepper']::text[], array['Labdanum', 'Benzoin', 'Orris']::text[], array['Vanilla absolute', 'Tonka bean', 'Amber']::text[], array['date-night', 'slow-sunday']::text[], array['warm', 'sweet']::text[], '12+ hours', 'Strong', '#9A5B2E', '/images/products/noire-02/front.svg', array['/images/products/noire-02/front.svg', '/images/products/noire-02/still.svg', '/images/products/noire-02/detail.svg']::text[], 365, 2, false, true, false, now() - interval '114 days')
on conflict (slug) do update set
  number = excluded.number, name = excluded.name, description = excluded.description,
  short_description = excluded.short_description, category = excluded.category, gender = excluded.gender,
  fragrance_family = excluded.fragrance_family, secondary_family = excluded.secondary_family,
  top_notes = excluded.top_notes, heart_notes = excluded.heart_notes, base_notes = excluded.base_notes,
  moods = excluded.moods, scent_profiles = excluded.scent_profiles, longevity = excluded.longevity,
  sillage = excluded.sillage, accent_color = excluded.accent_color, image_url = excluded.image_url,
  gallery_images = excluded.gallery_images, sort_order = excluded.sort_order, featured = excluded.featured,
  bestseller = excluded.bestseller, new_arrival = excluded.new_arrival;
insert into public.noire_product_variants (product_id, size_ml, price, stock_quantity, sku)
values
  ((select id from public.noire_products where slug = 'noire-02'), 30, 62000, 16, 'NO02-30'),
  ((select id from public.noire_products where slug = 'noire-02'), 50, 96000, 9, 'NO02-50'),
  ((select id from public.noire_products where slug = 'noire-02'), 100, 142000, 0, 'NO02-100')
on conflict (sku) do update set price = excluded.price, stock_quantity = excluded.stock_quantity;

-- NOIRÉ 03 — Citrus Veil
insert into public.noire_products (number, name, slug, description, short_description, currency, category, gender, fragrance_family, secondary_family, top_notes, heart_notes, base_notes, moods, scent_profiles, longevity, sillage, accent_color, image_url, gallery_images, sales_count, sort_order, featured, bestseller, new_arrival, created_at)
values (3, 'Citrus Veil', 'noire-03', 'The first cool hour of a bright morning. Calabrian bergamot and yuzu sparkle over petitgrain, then drift into neroli and green tea, light as linen. White musk and a whisper of vetiver keep the brightness close to skin, so it feels clean rather than loud.', 'Bergamot, yuzu and sheer neroli', 'NGN', 'Eau de Parfum', 'unisex', 'citrus', 'fresh', array['Bergamot', 'Yuzu', 'Petitgrain']::text[], array['Neroli', 'Green tea', 'Orange blossom']::text[], array['White musk', 'Vetiver']::text[], array['fresh-start']::text[], array['fresh', 'clean']::text[], '6–8 hours', 'Soft to moderate', '#B49A4E', '/images/products/noire-03/front.svg', array['/images/products/noire-03/front.svg', '/images/products/noire-03/still.svg', '/images/products/noire-03/detail.svg']::text[], 188, 3, true, false, false, now() - interval '108 days')
on conflict (slug) do update set
  number = excluded.number, name = excluded.name, description = excluded.description,
  short_description = excluded.short_description, category = excluded.category, gender = excluded.gender,
  fragrance_family = excluded.fragrance_family, secondary_family = excluded.secondary_family,
  top_notes = excluded.top_notes, heart_notes = excluded.heart_notes, base_notes = excluded.base_notes,
  moods = excluded.moods, scent_profiles = excluded.scent_profiles, longevity = excluded.longevity,
  sillage = excluded.sillage, accent_color = excluded.accent_color, image_url = excluded.image_url,
  gallery_images = excluded.gallery_images, sort_order = excluded.sort_order, featured = excluded.featured,
  bestseller = excluded.bestseller, new_arrival = excluded.new_arrival;
insert into public.noire_product_variants (product_id, size_ml, price, stock_quantity, sku)
values
  ((select id from public.noire_products where slug = 'noire-03'), 30, 42000, 30, 'NO03-30'),
  ((select id from public.noire_products where slug = 'noire-03'), 50, 68000, 26, 'NO03-50'),
  ((select id from public.noire_products where slug = 'noire-03'), 100, 98000, 14, 'NO03-100')
on conflict (sku) do update set price = excluded.price, stock_quantity = excluded.stock_quantity;

-- NOIRÉ 04 — After Rain
insert into public.noire_products (number, name, slug, description, short_description, currency, category, gender, fragrance_family, secondary_family, top_notes, heart_notes, base_notes, moods, scent_profiles, longevity, sillage, accent_color, image_url, gallery_images, sales_count, sort_order, featured, bestseller, new_arrival, created_at)
values (4, 'After Rain', 'noire-04', 'Petrichor, bottled. A cool ozonic accord and crushed violet leaf meet a hint of pear, before a mineral heart of wet stone and powdery iris. Vetiver and oakmoss ground it in the green, earthy calm that follows a downpour.', 'Wet stone, violet leaf and vetiver', 'NGN', 'Eau de Parfum', 'unisex', 'fresh', 'aquatic', array['Ozonic accord', 'Violet leaf', 'Pear']::text[], array['Wet stone accord', 'Iris', 'Lily of the valley']::text[], array['Vetiver', 'Oakmoss', 'Ambrette']::text[], array['fresh-start', 'slow-sunday']::text[], array['fresh', 'clean']::text[], '6–8 hours', 'Moderate', '#5F7375', '/images/products/noire-04/front.svg', array['/images/products/noire-04/front.svg', '/images/products/noire-04/still.svg', '/images/products/noire-04/detail.svg']::text[], 141, 4, false, false, false, now() - interval '102 days')
on conflict (slug) do update set
  number = excluded.number, name = excluded.name, description = excluded.description,
  short_description = excluded.short_description, category = excluded.category, gender = excluded.gender,
  fragrance_family = excluded.fragrance_family, secondary_family = excluded.secondary_family,
  top_notes = excluded.top_notes, heart_notes = excluded.heart_notes, base_notes = excluded.base_notes,
  moods = excluded.moods, scent_profiles = excluded.scent_profiles, longevity = excluded.longevity,
  sillage = excluded.sillage, accent_color = excluded.accent_color, image_url = excluded.image_url,
  gallery_images = excluded.gallery_images, sort_order = excluded.sort_order, featured = excluded.featured,
  bestseller = excluded.bestseller, new_arrival = excluded.new_arrival;
insert into public.noire_product_variants (product_id, size_ml, price, stock_quantity, sku)
values
  ((select id from public.noire_products where slug = 'noire-04'), 30, 42000, 22, 'NO04-30'),
  ((select id from public.noire_products where slug = 'noire-04'), 50, 68000, 20, 'NO04-50'),
  ((select id from public.noire_products where slug = 'noire-04'), 100, 98000, 10, 'NO04-100')
on conflict (sku) do update set price = excluded.price, stock_quantity = excluded.stock_quantity;

-- NOIRÉ 05 — Midnight Iris
insert into public.noire_products (number, name, slug, description, short_description, currency, category, gender, fragrance_family, secondary_family, top_notes, heart_notes, base_notes, moods, scent_profiles, longevity, sillage, accent_color, image_url, gallery_images, sales_count, sort_order, featured, bestseller, new_arrival, created_at)
values (5, 'Midnight Iris', 'noire-05', 'Iris after dark — cool, powdery and a little dangerous. Black pepper and bergamot cut through a heart of orris butter and violet, while vetiver, suede and patchouli give the flowers a shadow. Elegant, but never polite.', 'Powdered iris, black pepper and suede', 'NGN', 'Eau de Parfum', 'unisex', 'floral', 'woody', array['Black pepper', 'Bergamot']::text[], array['Iris', 'Orris butter', 'Violet']::text[], array['Vetiver', 'Suede', 'Patchouli']::text[], array['after-dark', 'quiet-luxury', 'main-character']::text[], array['floral', 'mysterious']::text[], '8–10 hours', 'Moderate', '#4A4458', '/images/products/noire-05/front.svg', array['/images/products/noire-05/front.svg', '/images/products/noire-05/still.svg', '/images/products/noire-05/detail.svg']::text[], 276, 5, true, false, false, now() - interval '96 days')
on conflict (slug) do update set
  number = excluded.number, name = excluded.name, description = excluded.description,
  short_description = excluded.short_description, category = excluded.category, gender = excluded.gender,
  fragrance_family = excluded.fragrance_family, secondary_family = excluded.secondary_family,
  top_notes = excluded.top_notes, heart_notes = excluded.heart_notes, base_notes = excluded.base_notes,
  moods = excluded.moods, scent_profiles = excluded.scent_profiles, longevity = excluded.longevity,
  sillage = excluded.sillage, accent_color = excluded.accent_color, image_url = excluded.image_url,
  gallery_images = excluded.gallery_images, sort_order = excluded.sort_order, featured = excluded.featured,
  bestseller = excluded.bestseller, new_arrival = excluded.new_arrival;
insert into public.noire_product_variants (product_id, size_ml, price, stock_quantity, sku)
values
  ((select id from public.noire_products where slug = 'noire-05'), 30, 54000, 3, 'NO05-30'),
  ((select id from public.noire_products where slug = 'noire-05'), 50, 85000, 14, 'NO05-50'),
  ((select id from public.noire_products where slug = 'noire-05'), 100, 126000, 8, 'NO05-100')
on conflict (sku) do update set price = excluded.price, stock_quantity = excluded.stock_quantity;

-- NOIRÉ 06 — Cedar Smoke
insert into public.noire_products (number, name, slug, description, short_description, currency, category, gender, fragrance_family, secondary_family, top_notes, heart_notes, base_notes, moods, scent_profiles, longevity, sillage, accent_color, image_url, gallery_images, sales_count, sort_order, featured, bestseller, new_arrival, created_at)
values (6, 'Cedar Smoke', 'noire-06', 'A cabin fire burning down to embers. Juniper and elemi bring a resinous chill, then Atlas cedar and guaiac wood meet the dark smoke of birch tar. Leather and labdanum close it out — rugged, dry and quietly magnetic.', 'Atlas cedar, birch tar and juniper', 'NGN', 'Eau de Parfum', 'masculine', 'woody', 'leather', array['Juniper', 'Black pepper', 'Elemi']::text[], array['Atlas cedar', 'Birch tar', 'Guaiac wood']::text[], array['Leather', 'Cade', 'Labdanum']::text[], array['after-dark', 'main-character']::text[], array['woody', 'spicy', 'mysterious']::text[], '10–12 hours', 'Strong', '#3B3631', '/images/products/noire-06/front.svg', array['/images/products/noire-06/front.svg', '/images/products/noire-06/still.svg', '/images/products/noire-06/detail.svg']::text[], 338, 6, false, true, false, now() - interval '90 days')
on conflict (slug) do update set
  number = excluded.number, name = excluded.name, description = excluded.description,
  short_description = excluded.short_description, category = excluded.category, gender = excluded.gender,
  fragrance_family = excluded.fragrance_family, secondary_family = excluded.secondary_family,
  top_notes = excluded.top_notes, heart_notes = excluded.heart_notes, base_notes = excluded.base_notes,
  moods = excluded.moods, scent_profiles = excluded.scent_profiles, longevity = excluded.longevity,
  sillage = excluded.sillage, accent_color = excluded.accent_color, image_url = excluded.image_url,
  gallery_images = excluded.gallery_images, sort_order = excluded.sort_order, featured = excluded.featured,
  bestseller = excluded.bestseller, new_arrival = excluded.new_arrival;
insert into public.noire_product_variants (product_id, size_ml, price, stock_quantity, sku)
values
  ((select id from public.noire_products where slug = 'noire-06'), 30, 54000, 20, 'NO06-30'),
  ((select id from public.noire_products where slug = 'noire-06'), 50, 85000, 16, 'NO06-50'),
  ((select id from public.noire_products where slug = 'noire-06'), 100, 126000, 11, 'NO06-100')
on conflict (sku) do update set price = excluded.price, stock_quantity = excluded.stock_quantity;

-- NOIRÉ 07 — Soft Skin
insert into public.noire_products (number, name, slug, description, short_description, currency, category, gender, fragrance_family, secondary_family, top_notes, heart_notes, base_notes, moods, scent_profiles, longevity, sillage, accent_color, image_url, gallery_images, sales_count, sort_order, featured, bestseller, new_arrival, created_at)
values (7, 'Soft Skin', 'noire-07', 'Your skin, only better. Airy aldehydes and a flicker of pink pepper melt into ambrette seed, iris and heliotrope. Clean musks and cashmeran settle like warm cotton — the kind of scent people lean in to notice.', 'Ambrette, iris and cashmere musk', 'NGN', 'Eau de Parfum', 'unisex', 'fresh', 'musk', array['Aldehydes', 'Pink pepper']::text[], array['Ambrette seed', 'Iris', 'Heliotrope']::text[], array['White musk', 'Cashmeran', 'Sandalwood']::text[], array['quiet-luxury', 'slow-sunday']::text[], array['clean', 'floral']::text[], '8–10 hours', 'Intimate', '#A88B78', '/images/products/noire-07/front.svg', array['/images/products/noire-07/front.svg', '/images/products/noire-07/still.svg', '/images/products/noire-07/detail.svg']::text[], 394, 7, false, true, false, now() - interval '84 days')
on conflict (slug) do update set
  number = excluded.number, name = excluded.name, description = excluded.description,
  short_description = excluded.short_description, category = excluded.category, gender = excluded.gender,
  fragrance_family = excluded.fragrance_family, secondary_family = excluded.secondary_family,
  top_notes = excluded.top_notes, heart_notes = excluded.heart_notes, base_notes = excluded.base_notes,
  moods = excluded.moods, scent_profiles = excluded.scent_profiles, longevity = excluded.longevity,
  sillage = excluded.sillage, accent_color = excluded.accent_color, image_url = excluded.image_url,
  gallery_images = excluded.gallery_images, sort_order = excluded.sort_order, featured = excluded.featured,
  bestseller = excluded.bestseller, new_arrival = excluded.new_arrival;
insert into public.noire_product_variants (product_id, size_ml, price, stock_quantity, sku)
values
  ((select id from public.noire_products where slug = 'noire-07'), 30, 54000, 28, 'NO07-30'),
  ((select id from public.noire_products where slug = 'noire-07'), 50, 85000, 22, 'NO07-50'),
  ((select id from public.noire_products where slug = 'noire-07'), 100, 126000, 15, 'NO07-100')
on conflict (sku) do update set price = excluded.price, stock_quantity = excluded.stock_quantity;

-- NOIRÉ 08 — Golden Hour
insert into public.noire_products (number, name, slug, description, short_description, currency, category, gender, fragrance_family, secondary_family, top_notes, heart_notes, base_notes, moods, scent_profiles, longevity, sillage, accent_color, image_url, gallery_images, sales_count, sort_order, featured, bestseller, new_arrival, created_at)
values (8, 'Golden Hour', 'noire-08', 'The last warm light of the day on bare shoulders. Bitter orange glows over jasmine sambac and orange blossom, with immortelle adding a sun-dried, honeyed depth. Amber, benzoin and sandalwood hold the light long after sunset.', 'Jasmine sambac, bitter orange and amber', 'NGN', 'Eau de Parfum', 'feminine', 'amber', 'floral', array['Bitter orange', 'Pink pepper']::text[], array['Jasmine sambac', 'Orange blossom', 'Immortelle']::text[], array['Amber', 'Benzoin', 'Sandalwood']::text[], array['date-night', 'main-character']::text[], array['warm', 'floral', 'sweet']::text[], '8–10 hours', 'Moderate to strong', '#A06E2C', '/images/products/noire-08/front.svg', array['/images/products/noire-08/front.svg', '/images/products/noire-08/still.svg', '/images/products/noire-08/detail.svg']::text[], 97, 8, true, false, true, now() - interval '13 days')
on conflict (slug) do update set
  number = excluded.number, name = excluded.name, description = excluded.description,
  short_description = excluded.short_description, category = excluded.category, gender = excluded.gender,
  fragrance_family = excluded.fragrance_family, secondary_family = excluded.secondary_family,
  top_notes = excluded.top_notes, heart_notes = excluded.heart_notes, base_notes = excluded.base_notes,
  moods = excluded.moods, scent_profiles = excluded.scent_profiles, longevity = excluded.longevity,
  sillage = excluded.sillage, accent_color = excluded.accent_color, image_url = excluded.image_url,
  gallery_images = excluded.gallery_images, sort_order = excluded.sort_order, featured = excluded.featured,
  bestseller = excluded.bestseller, new_arrival = excluded.new_arrival;
insert into public.noire_product_variants (product_id, size_ml, price, stock_quantity, sku)
values
  ((select id from public.noire_products where slug = 'noire-08'), 30, 54000, 25, 'NO08-30'),
  ((select id from public.noire_products where slug = 'noire-08'), 50, 85000, 20, 'NO08-50'),
  ((select id from public.noire_products where slug = 'noire-08'), 100, 126000, 12, 'NO08-100')
on conflict (sku) do update set price = excluded.price, stock_quantity = excluded.stock_quantity;

-- NOIRÉ 09 — Black Fig
insert into public.noire_products (number, name, slug, description, short_description, currency, category, gender, fragrance_family, secondary_family, top_notes, heart_notes, base_notes, moods, scent_profiles, longevity, sillage, accent_color, image_url, gallery_images, sales_count, sort_order, featured, bestseller, new_arrival, created_at)
values (9, 'Black Fig', 'noire-09', 'A fig split open in late summer. Green fig leaf and cardamom give way to the jammy sweetness of black fig and davana, rich but never cloying. Cedarwood, tonka and benzoin bring a creamy, woody finish that feels like a long lunch that turned into dinner.', 'Ripe fig, cardamom and tonka', 'NGN', 'Eau de Parfum', 'unisex', 'gourmand', 'woody', array['Fig leaf', 'Cardamom', 'Bergamot']::text[], array['Black fig', 'Davana', 'Coconut milk']::text[], array['Cedarwood', 'Tonka bean', 'Benzoin']::text[], array['slow-sunday', 'date-night']::text[], array['sweet', 'woody']::text[], '8–10 hours', 'Moderate', '#4B3A44', '/images/products/noire-09/front.svg', array['/images/products/noire-09/front.svg', '/images/products/noire-09/still.svg', '/images/products/noire-09/detail.svg']::text[], 84, 9, false, false, true, now() - interval '14 days')
on conflict (slug) do update set
  number = excluded.number, name = excluded.name, description = excluded.description,
  short_description = excluded.short_description, category = excluded.category, gender = excluded.gender,
  fragrance_family = excluded.fragrance_family, secondary_family = excluded.secondary_family,
  top_notes = excluded.top_notes, heart_notes = excluded.heart_notes, base_notes = excluded.base_notes,
  moods = excluded.moods, scent_profiles = excluded.scent_profiles, longevity = excluded.longevity,
  sillage = excluded.sillage, accent_color = excluded.accent_color, image_url = excluded.image_url,
  gallery_images = excluded.gallery_images, sort_order = excluded.sort_order, featured = excluded.featured,
  bestseller = excluded.bestseller, new_arrival = excluded.new_arrival;
insert into public.noire_product_variants (product_id, size_ml, price, stock_quantity, sku)
values
  ((select id from public.noire_products where slug = 'noire-09'), 30, 54000, 26, 'NO09-30'),
  ((select id from public.noire_products where slug = 'noire-09'), 50, 85000, 18, 'NO09-50'),
  ((select id from public.noire_products where slug = 'noire-09'), 100, 126000, 10, 'NO09-100')
on conflict (sku) do update set price = excluded.price, stock_quantity = excluded.stock_quantity;

-- NOIRÉ 10 — White Musk
insert into public.noire_products (number, name, slug, description, short_description, currency, category, gender, fragrance_family, secondary_family, top_notes, heart_notes, base_notes, moods, scent_profiles, longevity, sillage, accent_color, image_url, gallery_images, sales_count, sort_order, featured, bestseller, new_arrival, created_at)
values (10, 'White Musk', 'noire-10', 'Freshly laundered sheets in a sunlit room. Sparkling aldehydes and pear blossom lift a soft heart of lily of the valley, cotton flower and rose water. A cloud of white musk and cashmere wood makes it effortless to wear every single day.', 'Clean musk, pear blossom and cotton', 'NGN', 'Eau de Parfum', 'unisex', 'fresh', 'musk', array['Aldehydes', 'Bergamot', 'Pear blossom']::text[], array['Lily of the valley', 'Cotton flower', 'Rose water']::text[], array['White musk', 'Ambrette', 'Cashmere wood']::text[], array['fresh-start', 'quiet-luxury']::text[], array['clean', 'fresh']::text[], '6–8 hours', 'Soft', '#A79E92', '/images/products/noire-10/front.svg', array['/images/products/noire-10/front.svg', '/images/products/noire-10/still.svg', '/images/products/noire-10/detail.svg']::text[], 352, 10, false, true, false, now() - interval '66 days')
on conflict (slug) do update set
  number = excluded.number, name = excluded.name, description = excluded.description,
  short_description = excluded.short_description, category = excluded.category, gender = excluded.gender,
  fragrance_family = excluded.fragrance_family, secondary_family = excluded.secondary_family,
  top_notes = excluded.top_notes, heart_notes = excluded.heart_notes, base_notes = excluded.base_notes,
  moods = excluded.moods, scent_profiles = excluded.scent_profiles, longevity = excluded.longevity,
  sillage = excluded.sillage, accent_color = excluded.accent_color, image_url = excluded.image_url,
  gallery_images = excluded.gallery_images, sort_order = excluded.sort_order, featured = excluded.featured,
  bestseller = excluded.bestseller, new_arrival = excluded.new_arrival;
insert into public.noire_product_variants (product_id, size_ml, price, stock_quantity, sku)
values
  ((select id from public.noire_products where slug = 'noire-10'), 30, 42000, 34, 'NO10-30'),
  ((select id from public.noire_products where slug = 'noire-10'), 50, 68000, 28, 'NO10-50'),
  ((select id from public.noire_products where slug = 'noire-10'), 100, 98000, 16, 'NO10-100')
on conflict (sku) do update set price = excluded.price, stock_quantity = excluded.stock_quantity;

-- NOIRÉ 11 — Rose Noir
insert into public.noire_products (number, name, slug, description, short_description, currency, category, gender, fragrance_family, secondary_family, top_notes, heart_notes, base_notes, moods, scent_profiles, longevity, sillage, accent_color, image_url, gallery_images, sales_count, sort_order, featured, bestseller, new_arrival, created_at)
values (11, 'Rose Noir', 'noire-11', 'A rose with a secret. Saffron and pink pepper warm Turkish and Damask roses, deepened by a touch of geranium. Beneath, smoked oud, patchouli and incense turn the bouquet velvety and nocturnal — romantic, with an edge.', 'Dark rose, saffron and smoked oud', 'NGN', 'Extrait de Parfum', 'feminine', 'floral', 'spicy', array['Saffron', 'Pink pepper', 'Raspberry leaf']::text[], array['Turkish rose', 'Damask rose', 'Geranium']::text[], array['Oud', 'Patchouli', 'Incense']::text[], array['date-night', 'after-dark', 'main-character']::text[], array['floral', 'spicy', 'mysterious']::text[], '12+ hours', 'Strong', '#6E2B32', '/images/products/noire-11/front.svg', array['/images/products/noire-11/front.svg', '/images/products/noire-11/still.svg', '/images/products/noire-11/detail.svg']::text[], 231, 11, true, false, false, now() - interval '60 days')
on conflict (slug) do update set
  number = excluded.number, name = excluded.name, description = excluded.description,
  short_description = excluded.short_description, category = excluded.category, gender = excluded.gender,
  fragrance_family = excluded.fragrance_family, secondary_family = excluded.secondary_family,
  top_notes = excluded.top_notes, heart_notes = excluded.heart_notes, base_notes = excluded.base_notes,
  moods = excluded.moods, scent_profiles = excluded.scent_profiles, longevity = excluded.longevity,
  sillage = excluded.sillage, accent_color = excluded.accent_color, image_url = excluded.image_url,
  gallery_images = excluded.gallery_images, sort_order = excluded.sort_order, featured = excluded.featured,
  bestseller = excluded.bestseller, new_arrival = excluded.new_arrival;
insert into public.noire_product_variants (product_id, size_ml, price, stock_quantity, sku)
values
  ((select id from public.noire_products where slug = 'noire-11'), 30, 62000, 14, 'NO11-30'),
  ((select id from public.noire_products where slug = 'noire-11'), 50, 96000, 12, 'NO11-50'),
  ((select id from public.noire_products where slug = 'noire-11'), 100, 142000, 6, 'NO11-100')
on conflict (sku) do update set price = excluded.price, stock_quantity = excluded.stock_quantity;

-- NOIRÉ 12 — Desert Bloom
insert into public.noire_products (number, name, slug, description, short_description, currency, category, gender, fragrance_family, secondary_family, top_notes, heart_notes, base_notes, moods, scent_profiles, longevity, sillage, accent_color, image_url, gallery_images, sales_count, sort_order, featured, bestseller, new_arrival, created_at)
values (12, 'Desert Bloom', 'noire-12', 'Wildflowers that bloom against the odds. Blood orange and mandarin flash over a pinch of saffron, opening onto cactus flower, osmanthus and orange blossom. Sandalwood, ambrette and a trace of myrrh hold the warmth of sun-baked earth.', 'Blood orange, cactus flower and myrrh', 'NGN', 'Eau de Parfum', 'unisex', 'citrus', 'floral', array['Blood orange', 'Mandarin', 'Saffron']::text[], array['Cactus flower', 'Osmanthus', 'Orange blossom']::text[], array['Sandalwood', 'Ambrette', 'Myrrh']::text[], array['main-character', 'fresh-start']::text[], array['fresh', 'warm', 'floral']::text[], '8–10 hours', 'Moderate', '#A65A38', '/images/products/noire-12/front.svg', array['/images/products/noire-12/front.svg', '/images/products/noire-12/still.svg', '/images/products/noire-12/detail.svg']::text[], 63, 12, false, false, true, now() - interval '17 days')
on conflict (slug) do update set
  number = excluded.number, name = excluded.name, description = excluded.description,
  short_description = excluded.short_description, category = excluded.category, gender = excluded.gender,
  fragrance_family = excluded.fragrance_family, secondary_family = excluded.secondary_family,
  top_notes = excluded.top_notes, heart_notes = excluded.heart_notes, base_notes = excluded.base_notes,
  moods = excluded.moods, scent_profiles = excluded.scent_profiles, longevity = excluded.longevity,
  sillage = excluded.sillage, accent_color = excluded.accent_color, image_url = excluded.image_url,
  gallery_images = excluded.gallery_images, sort_order = excluded.sort_order, featured = excluded.featured,
  bestseller = excluded.bestseller, new_arrival = excluded.new_arrival;
insert into public.noire_product_variants (product_id, size_ml, price, stock_quantity, sku)
values
  ((select id from public.noire_products where slug = 'noire-12'), 30, 54000, 22, 'NO12-30'),
  ((select id from public.noire_products where slug = 'noire-12'), 50, 85000, 18, 'NO12-50'),
  ((select id from public.noire_products where slug = 'noire-12'), 100, 126000, 9, 'NO12-100')
on conflict (sku) do update set price = excluded.price, stock_quantity = excluded.stock_quantity;
