// Source of truth for the launch catalog.
// Used by scripts/generate-seed.mjs (→ supabase/seed.sql) and scripts/generate-art.mjs (→ public/images).

const tiers = {
  fresh: { 30: 42000, 50: 68000, 100: 98000 },
  signature: { 30: 54000, 50: 85000, 100: 126000 },
  extrait: { 30: 62000, 50: 96000, 100: 142000 },
};

export const products = [
  {
    number: 1,
    name: "Santal Obscur",
    family: "woody",
    secondary: "amber",
    gender: "unisex",
    category: "Eau de Parfum",
    short: "Smoked cedar, saffron and warm amber",
    description:
      "A low-lit room after the guests have gone. Saffron and pink pepper strike first, then settle into creamy sandalwood and cedar that has been gently smoked over papyrus. A base of amber and soft leather lingers on skin long into the night — quiet, assured and unmistakably yours.",
    top: ["Saffron", "Pink pepper", "Cardamom"],
    heart: ["Sandalwood", "Smoked cedar", "Papyrus"],
    base: ["Amber", "Soft leather", "Musk"],
    moods: ["after-dark", "quiet-luxury"],
    profiles: ["woody", "warm", "mysterious"],
    longevity: "10–12 hours",
    sillage: "Moderate to strong",
    tier: "signature",
    stock: { 30: 24, 50: 18, 100: 12 },
    salesCount: 412,
    featured: true,
    bestseller: true,
    newArrival: false,
    palette: { liquid: "#7A4E2D", backdrop: "#D9CBB8", floor: "#CDBCA6", accent: "#5B4636" },
  },
  {
    number: 2,
    name: "Velvet Amber",
    family: "amber",
    secondary: "gourmand",
    gender: "unisex",
    category: "Extrait de Parfum",
    short: "Labdanum, vanilla and a trace of clove",
    description:
      "Amber the way it should be: dense, glowing and slow to fade. Mandarin and clove open onto a heart of labdanum and benzoin softened with orris, before vanilla absolute and tonka bean wrap everything in warmth. An extrait concentration for evenings that deserve to be remembered.",
    top: ["Mandarin", "Clove", "Pink pepper"],
    heart: ["Labdanum", "Benzoin", "Orris"],
    base: ["Vanilla absolute", "Tonka bean", "Amber"],
    moods: ["date-night", "slow-sunday"],
    profiles: ["warm", "sweet"],
    longevity: "12+ hours",
    sillage: "Strong",
    tier: "extrait",
    stock: { 30: 16, 50: 9, 100: 0 },
    salesCount: 365,
    featured: false,
    bestseller: true,
    newArrival: false,
    palette: { liquid: "#B0662B", backdrop: "#E2CDB4", floor: "#D5BC9F", accent: "#9A5B2E" },
  },
  {
    number: 3,
    name: "Citrus Veil",
    family: "citrus",
    secondary: "fresh",
    gender: "unisex",
    category: "Eau de Parfum",
    short: "Bergamot, yuzu and sheer neroli",
    description:
      "The first cool hour of a bright morning. Calabrian bergamot and yuzu sparkle over petitgrain, then drift into neroli and green tea, light as linen. White musk and a whisper of vetiver keep the brightness close to skin, so it feels clean rather than loud.",
    top: ["Bergamot", "Yuzu", "Petitgrain"],
    heart: ["Neroli", "Green tea", "Orange blossom"],
    base: ["White musk", "Vetiver"],
    moods: ["fresh-start"],
    profiles: ["fresh", "clean"],
    longevity: "6–8 hours",
    sillage: "Soft to moderate",
    tier: "fresh",
    stock: { 30: 30, 50: 26, 100: 14 },
    salesCount: 188,
    featured: true,
    bestseller: false,
    newArrival: false,
    palette: { liquid: "#D9C27A", backdrop: "#ECE6D4", floor: "#E0D8C1", accent: "#B49A4E" },
  },
  {
    number: 4,
    name: "After Rain",
    family: "fresh",
    secondary: "aquatic",
    gender: "unisex",
    category: "Eau de Parfum",
    short: "Wet stone, violet leaf and vetiver",
    description:
      "Petrichor, bottled. A cool ozonic accord and crushed violet leaf meet a hint of pear, before a mineral heart of wet stone and powdery iris. Vetiver and oakmoss ground it in the green, earthy calm that follows a downpour.",
    top: ["Ozonic accord", "Violet leaf", "Pear"],
    heart: ["Wet stone accord", "Iris", "Lily of the valley"],
    base: ["Vetiver", "Oakmoss", "Ambrette"],
    moods: ["fresh-start", "slow-sunday"],
    profiles: ["fresh", "clean"],
    longevity: "6–8 hours",
    sillage: "Moderate",
    tier: "fresh",
    stock: { 30: 22, 50: 20, 100: 10 },
    salesCount: 141,
    featured: false,
    bestseller: false,
    newArrival: false,
    palette: { liquid: "#8FA2A4", backdrop: "#D6D9D4", floor: "#C6CBC5", accent: "#5F7375" },
  },
  {
    number: 5,
    name: "Midnight Iris",
    family: "floral",
    secondary: "woody",
    gender: "unisex",
    category: "Eau de Parfum",
    short: "Powdered iris, black pepper and suede",
    description:
      "Iris after dark — cool, powdery and a little dangerous. Black pepper and bergamot cut through a heart of orris butter and violet, while vetiver, suede and patchouli give the flowers a shadow. Elegant, but never polite.",
    top: ["Black pepper", "Bergamot"],
    heart: ["Iris", "Orris butter", "Violet"],
    base: ["Vetiver", "Suede", "Patchouli"],
    moods: ["after-dark", "quiet-luxury", "main-character"],
    profiles: ["floral", "mysterious"],
    longevity: "8–10 hours",
    sillage: "Moderate",
    tier: "signature",
    stock: { 30: 3, 50: 14, 100: 8 },
    salesCount: 276,
    featured: true,
    bestseller: false,
    newArrival: false,
    palette: { liquid: "#5E5470", backdrop: "#CFCAD0", floor: "#BFB9C0", accent: "#4A4458" },
  },
  {
    number: 6,
    name: "Cedar Smoke",
    family: "woody",
    secondary: "leather",
    gender: "masculine",
    category: "Eau de Parfum",
    short: "Atlas cedar, birch tar and juniper",
    description:
      "A cabin fire burning down to embers. Juniper and elemi bring a resinous chill, then Atlas cedar and guaiac wood meet the dark smoke of birch tar. Leather and labdanum close it out — rugged, dry and quietly magnetic.",
    top: ["Juniper", "Black pepper", "Elemi"],
    heart: ["Atlas cedar", "Birch tar", "Guaiac wood"],
    base: ["Leather", "Cade", "Labdanum"],
    moods: ["after-dark", "main-character"],
    profiles: ["woody", "spicy", "mysterious"],
    longevity: "10–12 hours",
    sillage: "Strong",
    tier: "signature",
    stock: { 30: 20, 50: 16, 100: 11 },
    salesCount: 338,
    featured: false,
    bestseller: true,
    newArrival: false,
    palette: { liquid: "#4E4239", backdrop: "#C9C2B8", floor: "#B9B1A6", accent: "#3B3631" },
  },
  {
    number: 7,
    name: "Soft Skin",
    family: "fresh",
    secondary: "musk",
    gender: "unisex",
    category: "Eau de Parfum",
    short: "Ambrette, iris and cashmere musk",
    description:
      "Your skin, only better. Airy aldehydes and a flicker of pink pepper melt into ambrette seed, iris and heliotrope. Clean musks and cashmeran settle like warm cotton — the kind of scent people lean in to notice.",
    top: ["Aldehydes", "Pink pepper"],
    heart: ["Ambrette seed", "Iris", "Heliotrope"],
    base: ["White musk", "Cashmeran", "Sandalwood"],
    moods: ["quiet-luxury", "slow-sunday"],
    profiles: ["clean", "floral"],
    longevity: "8–10 hours",
    sillage: "Intimate",
    tier: "signature",
    stock: { 30: 28, 50: 22, 100: 15 },
    salesCount: 394,
    featured: false,
    bestseller: true,
    newArrival: false,
    palette: { liquid: "#D7BFAE", backdrop: "#E8DDD3", floor: "#DCCFC3", accent: "#A88B78" },
  },
  {
    number: 8,
    name: "Golden Hour",
    family: "amber",
    secondary: "floral",
    gender: "feminine",
    category: "Eau de Parfum",
    short: "Jasmine sambac, bitter orange and amber",
    description:
      "The last warm light of the day on bare shoulders. Bitter orange glows over jasmine sambac and orange blossom, with immortelle adding a sun-dried, honeyed depth. Amber, benzoin and sandalwood hold the light long after sunset.",
    top: ["Bitter orange", "Pink pepper"],
    heart: ["Jasmine sambac", "Orange blossom", "Immortelle"],
    base: ["Amber", "Benzoin", "Sandalwood"],
    moods: ["date-night", "main-character"],
    profiles: ["warm", "floral", "sweet"],
    longevity: "8–10 hours",
    sillage: "Moderate to strong",
    tier: "signature",
    stock: { 30: 25, 50: 20, 100: 12 },
    salesCount: 97,
    featured: true,
    bestseller: false,
    newArrival: true,
    palette: { liquid: "#C48A3F", backdrop: "#E6D3B6", floor: "#D9C29F", accent: "#A06E2C" },
  },
  {
    number: 9,
    name: "Black Fig",
    family: "gourmand",
    secondary: "woody",
    gender: "unisex",
    category: "Eau de Parfum",
    short: "Ripe fig, cardamom and tonka",
    description:
      "A fig split open in late summer. Green fig leaf and cardamom give way to the jammy sweetness of black fig and davana, rich but never cloying. Cedarwood, tonka and benzoin bring a creamy, woody finish that feels like a long lunch that turned into dinner.",
    top: ["Fig leaf", "Cardamom", "Bergamot"],
    heart: ["Black fig", "Davana", "Coconut milk"],
    base: ["Cedarwood", "Tonka bean", "Benzoin"],
    moods: ["slow-sunday", "date-night"],
    profiles: ["sweet", "woody"],
    longevity: "8–10 hours",
    sillage: "Moderate",
    tier: "signature",
    stock: { 30: 26, 50: 18, 100: 10 },
    salesCount: 84,
    featured: false,
    bestseller: false,
    newArrival: true,
    palette: { liquid: "#5A3F4C", backdrop: "#D3C6C6", floor: "#C3B4B4", accent: "#4B3A44" },
  },
  {
    number: 10,
    name: "White Musk",
    family: "fresh",
    secondary: "musk",
    gender: "unisex",
    category: "Eau de Parfum",
    short: "Clean musk, pear blossom and cotton",
    description:
      "Freshly laundered sheets in a sunlit room. Sparkling aldehydes and pear blossom lift a soft heart of lily of the valley, cotton flower and rose water. A cloud of white musk and cashmere wood makes it effortless to wear every single day.",
    top: ["Aldehydes", "Bergamot", "Pear blossom"],
    heart: ["Lily of the valley", "Cotton flower", "Rose water"],
    base: ["White musk", "Ambrette", "Cashmere wood"],
    moods: ["fresh-start", "quiet-luxury"],
    profiles: ["clean", "fresh"],
    longevity: "6–8 hours",
    sillage: "Soft",
    tier: "fresh",
    stock: { 30: 34, 50: 28, 100: 16 },
    salesCount: 352,
    featured: false,
    bestseller: true,
    newArrival: false,
    palette: { liquid: "#E4DDD2", backdrop: "#EDE8E1", floor: "#E1DAD0", accent: "#A79E92" },
  },
  {
    number: 11,
    name: "Rose Noir",
    family: "floral",
    secondary: "spicy",
    gender: "feminine",
    category: "Extrait de Parfum",
    short: "Dark rose, saffron and smoked oud",
    description:
      "A rose with a secret. Saffron and pink pepper warm Turkish and Damask roses, deepened by a touch of geranium. Beneath, smoked oud, patchouli and incense turn the bouquet velvety and nocturnal — romantic, with an edge.",
    top: ["Saffron", "Pink pepper", "Raspberry leaf"],
    heart: ["Turkish rose", "Damask rose", "Geranium"],
    base: ["Oud", "Patchouli", "Incense"],
    moods: ["date-night", "after-dark", "main-character"],
    profiles: ["floral", "spicy", "mysterious"],
    longevity: "12+ hours",
    sillage: "Strong",
    tier: "extrait",
    stock: { 30: 14, 50: 12, 100: 6 },
    salesCount: 231,
    featured: true,
    bestseller: false,
    newArrival: false,
    palette: { liquid: "#6E2B32", backdrop: "#D6C3BF", floor: "#C8B1AC", accent: "#6E2B32" },
  },
  {
    number: 12,
    name: "Desert Bloom",
    family: "citrus",
    secondary: "floral",
    gender: "unisex",
    category: "Eau de Parfum",
    short: "Blood orange, cactus flower and myrrh",
    description:
      "Wildflowers that bloom against the odds. Blood orange and mandarin flash over a pinch of saffron, opening onto cactus flower, osmanthus and orange blossom. Sandalwood, ambrette and a trace of myrrh hold the warmth of sun-baked earth.",
    top: ["Blood orange", "Mandarin", "Saffron"],
    heart: ["Cactus flower", "Osmanthus", "Orange blossom"],
    base: ["Sandalwood", "Ambrette", "Myrrh"],
    moods: ["main-character", "fresh-start"],
    profiles: ["fresh", "warm", "floral"],
    longevity: "8–10 hours",
    sillage: "Moderate",
    tier: "signature",
    stock: { 30: 22, 50: 18, 100: 9 },
    salesCount: 63,
    featured: false,
    bestseller: false,
    newArrival: true,
    palette: { liquid: "#C9764F", backdrop: "#E5CFBF", floor: "#D8BDA9", accent: "#A65A38" },
  },
];

export const sizes = [30, 50, 100];

export function priceFor(product, size) {
  return tiers[product.tier][size];
}

export function slugFor(product) {
  return `noire-${String(product.number).padStart(2, "0")}`;
}

export function imagesFor(product) {
  const base = `/images/products/${slugFor(product)}`;
  return {
    imageUrl: `${base}/front.svg`,
    gallery: [`${base}/front.svg`, `${base}/still.svg`, `${base}/detail.svg`],
  };
}
