// Generates supabase/seed.sql from scripts/catalog.mjs.
// Usage: node scripts/generate-seed.mjs

import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { products, sizes, priceFor, slugFor, imagesFor } from "./catalog.mjs";

const q = (value) => (value === null || value === undefined ? "null" : `'${String(value).replace(/'/g, "''")}'`);
const arr = (values) => `array[${values.map(q).join(", ")}]::text[]`;

const lines = [
  "-- NOIRÉ launch catalog. Generated by scripts/generate-seed.mjs — edit scripts/catalog.mjs instead.",
  "-- Safe to re-run: products are upserted by slug and variants by SKU.",
  "",
];

products.forEach((p, index) => {
  const slug = slugFor(p);
  const { imageUrl, gallery } = imagesFor(p);
  // Stagger creation dates so "Newest" sorting reflects the release order (new arrivals last).
  const daysAgo = p.newArrival ? 6 + index : 120 - index * 6;

  lines.push(`-- NOIRÉ ${String(p.number).padStart(2, "0")} — ${p.name}`);
  lines.push(
    `insert into public.noire_products (number, name, slug, description, short_description, currency, category, gender, fragrance_family, secondary_family, top_notes, heart_notes, base_notes, moods, scent_profiles, longevity, sillage, accent_color, image_url, gallery_images, sales_count, sort_order, featured, bestseller, new_arrival, created_at)
values (${p.number}, ${q(p.name)}, ${q(slug)}, ${q(p.description)}, ${q(p.short)}, 'NGN', ${q(p.category)}, ${q(p.gender)}, ${q(p.family)}, ${q(p.secondary)}, ${arr(p.top)}, ${arr(p.heart)}, ${arr(p.base)}, ${arr(p.moods)}, ${arr(p.profiles)}, ${q(p.longevity)}, ${q(p.sillage)}, ${q(p.palette.accent)}, ${q(imageUrl)}, ${arr(gallery)}, ${p.salesCount}, ${p.number}, ${p.featured}, ${p.bestseller}, ${p.newArrival}, now() - interval '${daysAgo} days')
on conflict (slug) do update set
  number = excluded.number, name = excluded.name, description = excluded.description,
  short_description = excluded.short_description, category = excluded.category, gender = excluded.gender,
  fragrance_family = excluded.fragrance_family, secondary_family = excluded.secondary_family,
  top_notes = excluded.top_notes, heart_notes = excluded.heart_notes, base_notes = excluded.base_notes,
  moods = excluded.moods, scent_profiles = excluded.scent_profiles, longevity = excluded.longevity,
  sillage = excluded.sillage, accent_color = excluded.accent_color, image_url = excluded.image_url,
  gallery_images = excluded.gallery_images, sort_order = excluded.sort_order, featured = excluded.featured,
  bestseller = excluded.bestseller, new_arrival = excluded.new_arrival;`,
  );

  const variantValues = sizes
    .map(
      (size) =>
        `  ((select id from public.noire_products where slug = ${q(slug)}), ${size}, ${priceFor(p, size)}, ${p.stock[size]}, ${q(`NO${String(p.number).padStart(2, "0")}-${size}`)})`,
    )
    .join(",\n");
  lines.push(
    `insert into public.noire_product_variants (product_id, size_ml, price, stock_quantity, sku)
values
${variantValues}
on conflict (sku) do update set price = excluded.price, stock_quantity = excluded.stock_quantity;`,
  );
  lines.push("");
});

const target = fileURLToPath(new URL("../supabase/seed.sql", import.meta.url));
writeFileSync(target, lines.join("\n"));
console.log(`Wrote ${products.length} products to ${target}`);
